### ISSUE TITLE
Add steps to compile and run .kt files inside container in ReadMe.md

### ISSUE THREAD

**Issue by RotBolt** [Zenika/docker-kotlin#45]
To compile the file stored in my file system 
for eg. `hello.kt` under `/home/$USER` directory

I ran `docker container run -it -v /home/kaendagger --rm zenika/kotlin kotlinc hello.kt`

I mounted my directory in container.
but docker-kotlin is unable to find the file and shows this error
`error: source file or directory not found: hello.kt`

Please add steps to build and run .kt files inside container in ReadMe.md

**Comment by nlepage** [comment]
Hi

added a new example in the [usage section](https://github.com/Zenika/docker-kotlin#usage) and a [full example](https://github.com/Zenika/docker-kotlin/tree/master/examples/build-jar) in the examples directory.

Thx for your interest.
